searchbot/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("users/", include("users.urls", namespace="users")),
    path("searches/", include("searches.urls", namespace="searches")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("<int:pk>", views.view, name="view"),
    path("<int:pk>/update", views.UserUpdate.as_view(), name="update"),
    path("change_password", views.user_change_pass, name="change_password"),
]

searchbot/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "searchbot/home.html")


def about(request):
    return render(request, "searchbot/about.html")

templates/searchbot/about.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h2>About</h2>

    <p>
        This is an app created by Gregory Ottley using Python and Django to
        check websites and see if items are available.
    </p>

    <p>
        The code is designed to loop through a list of urls, check for a
        specific phrase added by a user, and if that phrase is no longer there,
        it assumes the item is now available.
    </p>

    <p>
        If you want to know more, contact me at
        <a href="mailto:hello@gregottley.co.uk">hello@gregottley.co.uk</a>
    </p>

    <p>
        You can view the code for the project at
        <a href="https://github.com/gjdj93/django_search_bot" target="_blank"
            >Github</a
        >
    </p>
</div>
{% endblock %}

templates/searchbot/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">SearchBot</a>
    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == '/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li
                class="nav-item {% if request.path == '/about' %}active{% endif %}"
            >
                <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                >
                    {{ user.username }}
                </a>
                <div
                    class="dropdown-menu dropdown-menu-right"
                    aria-labelledby="navbarDropdown"
                >
                    {% if request.user.is_superuser %}
                    <a class="dropdown-item" href="{% url 'users:index' %}"
                        >View Users</a
                    >
                    {% else %}
                    <a class="dropdown-item" href="{% url 'users:index' %}"
                        >Profile</a
                    >
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout' %}"
                        >Logout</a
                    >
                </div>
            </li>
            {% else %}
            <li
                class="nav-item {% if request.path == '/users/login' %}active{% endif %}"
            >
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/searchbot/home.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h2>Homepage</h2>

    <p>Searching for when an item will be back in stock?</p>
    <p>Leave it to Searchbot - we'll let you know!</p>

    {% if not user.is_authenticated %}
    <p>
        <a class="btn btn-primary" href="{% url 'users:login' %}">Login</a> or
        <a class="btn btn-primary" href="{% url 'users:register' %}"
            >Register</a
        >
        to add a search item
    </p>
    {% endif %}
</div>
{% endblock %}

templates/searchbot/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>SearchBot</title>
        <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"
        ></script>
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous"
        />
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"
        ></script>
        <style>
            .container {
                padding-top: 2em;
                padding-bottom: 2em;
            }
        </style>
    </head>
    <body>
        {% include "searchbot/header.html" %} {% block content %} {% endblock %}
    </body>
</html>