searchbot/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("users/", include("users.urls", namespace="users")),
    path("searches/", include("searches.urls", namespace="searches")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

searches/urls.py
from django.urls import path

from . import views

app_name = "searches"

urlpatterns = [
    path("create", views.create, name="create"),
    path("<int:pk>/view", views.view, name="view"),
    path("<int:pk>/update", views.SearchUpdate.as_view(), name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
    path("<int:pk>/found", views.found, name="found"),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("<int:pk>", views.view, name="view"),
    path("<int:pk>/update", views.UserUpdate.as_view(), name="update"),
    path("change_password", views.user_change_pass, name="change_password"),
]

searches/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.
class Search(models.Model):
    """
    A model to store the product info a user wants to search for.
    """

    name = models.CharField(max_length=255, help_text="The product name")
    url = models.CharField(max_length=1024, help_text="The url to the product")
    phrase = models.CharField(
        max_length=255,
        help_text="This phrase will be searched on the website - if the phrase is not there then the item should be in stock",
    )
    date_added = models.DateTimeField(default=timezone.now, blank=True)
    found = models.BooleanField(default=False)
    date_found = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        app_label = "searches"
        verbose_name_plural = "searches"

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

users/views.py
from ast import Pass
from django.shortcuts import render, redirect, get_object_or_404
from .forms import NewUserForm
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    PasswordResetForm,
)
from django.core.exceptions import PermissionDenied
from searches.models import Search
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from .services import send_register_email

# Create your views here.
def index(request):
    context = {}
    if request.user.is_superuser:
        context["users"] = User.objects.filter(is_superuser=False)
        return render(request, "users/index.html", context=context)
    searches = Search.objects.filter(user=request.user)
    context["searches"] = searches
    return render(request, "users/profile.html", context=context)


def view(request, pk):
    if not request.user.is_superuser:
        raise PermissionDenied

    u = get_object_or_404(User, pk=pk)

    return render(request, "users/view.html", context={"user": u})


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            send_register_email(user)
            return redirect("users:index")
        messages.error(request, "Registration invalid.")
    form = NewUserForm()
    return render(
        request=request,
        template_name="users/register.html",
        context={"register_form": form},
    )


def login_request(request):
    if request.user.is_authenticated:
        return redirect("users:index")
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are logged in as {username}.")
                return redirect("users:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
        print(form.errors)
    form = AuthenticationForm()
    return render(
        request, template_name="users/login.html", context={"login_form": form}
    )


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("index")


class UserUpdate(UpdateView):
    model = User
    fields = ("username", "email", "first_name", "last_name")

    template_name = "users/edit.html"
    success_url = "/users/"


def user_change_pass(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated!")
            return redirect("users:change_password")
    form = PasswordChangeForm(request.user)
    return render(
        request=request,
        template_name="users/change_password.html",
        context={"form": form},
    )


def user_reset_pass(request):
    form = PasswordResetForm()
    return render(
        request=request,
        template_name="users/reset_password.html",
        context={"form": form},
    )

templates/users/change_password.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h3>Change password</h3>
    {% load crispy_forms_tags %}
    <form method="post" action="" class="my-4">
        {% csrf_token %} {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
    {% if form.errors %} {% for field in form %} {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %} {% endfor %} {% endif %}
    <p>
        If you can't remember your password, you can
        <a href="{% url 'password_reset' %}">reset it here</a>.
    </p>
</div>
{% endblock %}

templates/users/edit.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h2>{{ form_type }} Search</h2>
    {% load crispy_forms_tags %}
    <form method="post" action="" class="my-4">
        {% csrf_token %} {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
    {% if form.errors %} {% for field in form %} {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %} {% endfor %} {% endif %}
</div>
{% endblock %}

templates/users/index.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h2>Users Index</h2>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Searches</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for u in users %}
                <tr>
                    <td>{{ u.username }}</td>
                    <td>{{ u.first_name }}</td>
                    <td>{{ u.last_name }}</td>
                    <td>{{ u.email }}</td>
                    <td>{{ u.search_set.count }}</td>
                    <td>
                        <a href="{% url 'users:view' u.id %}">View</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/users/login.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h2>Login</h2>
    {% load crispy_forms_tags %}
    <form method="post" action="" class="my-4">
        {% csrf_token %} {{ login_form|crispy }}
        <button class="btn btn-primary" type="submit">Login</button>
    </form>
    {% if messages %} {% for msg in messages %}
    <div class="alert alert-danger my-4">
        <strong>{{ msg }}</strong>
    </div>
    {% endfor %} {% endif %}
    <p>
        If you can't remember your password,
        <a href="{% url 'password_reset' %}">reset it here</a>.
    </p>
    <p>
        If you don't have an account yet,
        <a href="{% url 'users:register' %}">register</a> instead.
    </p>
</div>
{% endblock %}

templates/users/profile.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <a class="btn btn-primary" href="{% url 'searches:create' %}"
        >Create New Search</a
    >
    <a href="{% url 'users:update' user.id %}" class="btn btn-secondary"
        >Edit Profile</a
    >
    <a href="{% url 'users:change_password' %}" class="btn btn-secondary"
        >Change Password</a
    >
    <h4>Existing Searches</h4>
    {% if searches %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Search Phrase</th>
                    <th>Found</th>
                    <th>Date Added</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for s in searches %}
                <tr>
                    <td>{{ s.name }}</td>
                    <td>{{ s.url }}</td>
                    <td>{{ s.phrase }}</td>
                    <td>{{ s.found }} {{ s.date_found|date:"d/m/Y" }}</td>
                    <td>{{ s.date_added|date:"d/m/Y" }}</td>
                    <td>
                        <a href="{% url 'searches:view' s.id %}">View</a>
                        <a href="{% url 'searches:update' s.id %}">Edit</a>
                        <a href="{% url 'searches:delete' s.id %}?next=/users/"
                            >Delete</a
                        >
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>
        You don't have any searches. Why not
        <a href="{% url 'searches:create' %}">create one?</a>
    </p>
    {% endif %}
</div>
{% endblock %}

templates/users/register.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h2>Register</h2>
    {% load crispy_forms_tags %}
    <form method="post" action="" class="my-4">
        {% csrf_token %} {{ register_form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
    </form>
    {% if messages %} {% for msg in messages %}
    <div class="alert alert-danger my-4">
        <strong>{{ msg }}</strong>
    </div>
    {% endfor %} {% endif %}
    <p>
        If you already have an account,
        <a href="{% url 'users:login' %}">login</a> instead.
    </p>
</div>
{% endblock %}

templates/users/reset_password.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h3>Reset Password</h3>
    {% load crispy_forms_tags %}
    <form method="post" action="" class="my-4">
        {% csrf_token %} {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Reset</button>
    </form>
    {% if form.errors %} {% for field in form %} {% for error in field.errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %} {% endfor %} {% endif %}
</div>
{% endblock %}

templates/users/view.html
{% extends "searchbot/index.html" %} {% block content %}
<div class="container">
    <h3>{{ user.firstname }} {{ user.lastname }}</h3>

    <h4>User Searches</h4>
    {% if user.search_set %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>URL</th>
                    <th>Search Phrase</th>
                    <th>Found</th>
                    <th>Date Added</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for s in user.search_set.all %}
                <tr>
                    <td>{{ s.name }}</td>
                    <td>{{ s.url }}</td>
                    <td>{{ s.phrase }}</td>
                    <td>{{ s.found }} {{ s.date_found|date:"d/m/Y" }}</td>
                    <td>{{ s.date_added|date:"d/m/Y" }}</td>
                    <td>
                        <a href="{% url 'searches:view' s.id %}">View</a>
                        <a href="{% url 'searches:update' s.id %}">Edit</a>
                        <a href="{% url 'searches:delete' s.id %}?next=/users/"
                            >Delete</a
                        >
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>This user doesn't have any searches.</p>
    {% endif %} {% endblock %}
</div>